name = "backend"
compatibility_date = "2024-07-23"

[vars]
JWT_SECRET = "mysecret"
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiOTY2YWRkN2YtZDUzNi00ZGU2LTg0ZWUtOTJmOTE0YjgxMTRlIiwidGVuYW50X2lkIjoiYTRmNDg3NWYyNzM5MjA4ZDIwOGQzMjIyM2I5MGZlOWNmNTQ3MGUxZGFlZTMxOTEwNjVmMzU1ZGNlNjY5NmE3NSIsImludGVybmFsX3NlY3JldCI6IjEyNjQ4OWI2LTgzN2MtNGFkZC05ZTMzLWI5ODY3NTEzMWEwMCJ9.11gKs3kwyIrgjU490c_huGzIRTuY8sSmwP6CL7xOrN4"